name: pr_worklow
on:
  pull_request:
    types: [opened, closed, reopened]
jobs:
  pr_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log a Pr type message
        run: "echo 'Pull Request event detected: ${{ github.event.action }}'"